### PR TITLE
Merging Funktionale into Kategory repository

### PR DESCRIPTION
**Pull request by FPerezP**
This PR merges Funktionale repository into Kategory one keeping git history from both repositories.

*Conflict resolutions:*
_.gitignore_
I removed the Funktionale

_README.md_
Content from both repos have been kept.

### CODE REVIEW

**Comment by pakoito** [comment]
If it still fails after the merge I can take a look tonight.

**Comment by JorgeCastilloPrz** [comment]
Is this the idea ? To bring in Funktionale modules along with the Kategory ones to eventually merge all of them together? or how is it gonna work?

**Comment by pakoito** [comment]
@JorgeCastilloPrz the first step is to import the files & the full story. Then we're going on lockdown & refactor until we're ready. So a bunch of fun stuff to do this xmas if you'd like to join along!

**Comment by JorgeCastilloPrz** [comment]
Sounds good :+1:

**Comment by pakoito** [comment]
That "tonight" may become "this weekend" :p

**Pull request merged**
