### PR TITLE
IndexedStateT

### PR DESCRIPTION
**Pull request by nomisRev**
[Here you can find some more info under ](https://typelevel.org/cats/datatypes/state#changing-states) you can find some more info.

I have also attempted to make an proposal to improve the issue we have with alias/objects. The solution is a little awkward but for the user it "feels" the same.

Since `State`, `IndexedState`, `StateT` are all `IndexedStateT` with fixed type arguments I thought it would be very important for readability/usability to type alias these since this was already very tedious. As a result we cannot create `object State` and we thus lose the `object State` invoke overload. Therefore I created a function with a capital `S` to emulate to constructor. I first had this lowercase but my goal was to implement `IndexedStateT` with minimal changes to the docs to proof that the impact is minimal.

```kotlin
typealias State<S, A> = IndexedState<S, S, A>
fun <S, A> State(run: (S) -> Tuple2<S, A>): State<S, A> = IndexedStateT(Id(run.andThen { Id(it) }))
```

Since we cannot create `object State` since it conflicts with `typealias State<S, A>`. First of all I renamed the existing `object State` to `object StateId` and created a `fun State(): StateId` so you can access it `State().monad<Stack>()` instead of `State.monad<Stack>()`. I tried `val State: StateId` but that also conflicted with the `typealias`.

You can now define functions `fun stateOperation(): State<Stack, String> = TODO()`

There is something very awkward [https://github.com/kategory/kategory/compare/simon-indexedstatet?expand=1#diff-eb40df2419c8c1dc5877441142d31222R88](here) that I have not figured out yet. 

If you call it without the extra type parameters for `binding` like `fun stackOperations() = State().monad<Stack>().binding` it fails following error and I am unsure why. Adding a return type `State<Stack,Option<String>>` does not solve the problem.

```
Error:Kotlin: [Internal Error] org.jetbrains.kotlin.codegen.CompilationException: Back-end (JVM) Internal error: Cannot serialize error type: [ERROR : Unknown type parameter 2]
Cause: Cannot serialize error type: [ERROR : Unknown type parameter 2]
File being compiled and position: (25,56) in kategory/kategory-core/src/main/kotlin/kategory/predef.kt
PsiElement: {
    val a = push("a").bind()
    val b = pop().bind()
    val c = pop().bind()
    yields(c)
}
The root cause was thrown at: SerializerExtension.kt:62
	at org.jetbrains.kotlin.codegen.ExpressionCodegen.genQualified(ExpressionCodegen.java:322)
	at org.jetbrains.kotlin.codegen.ExpressionCodegen.genQualified(ExpressionCodegen.java:288)
	at org.jetbrains.kotlin.codegen.ExpressionCodegen.gen(ExpressionCodegen.java:328)
	at org.jetbrains.kotlin.codegen.CallGenerator$DefaultCallGenerator.genValueAndPut(CallGenerator.kt:64)
	at org.jetbrains.kotlin.codegen.CallBasedArgumentGenerator.generateExpression(CallBasedArgumentGenerator.java:62)
	at org.jetbrains.kotlin.codegen.ArgumentGenerator.generate(ArgumentGenerator.kt:68)
	at org.jetbrains.kotlin.codegen.ExpressionCodegen.invokeMethodWithArguments(ExpressionCodegen.java:2243)
	at org.jetbrains.kotlin.codegen.ExpressionCodegen.invokeMethodWithArguments(ExpressionCodegen.java:2221)
	at org.jetbrains.kotlin.codegen.Callable$invokeMethodWithArguments$1.invoke(Callable.kt:44)
	at org.jetbrains.kotlin.codegen.Callable$invokeMethodWithArguments$1.invoke(Callable.kt:23)
	at org.jetbrains.kotlin.codegen.OperationStackValue.putSelector(StackValue.kt:75)
	at org.jetbrains.kotlin.codegen.StackValue.put(StackValue.java:105)
	at org.jetbrains.kotlin.codegen.StackValue.put(StackValue.java:98)
	at org.jetbrains.kotlin.codegen.StackValue.moveToTopOfStack(StackValue.java:94)
	at org.jetbrains.kotlin.codegen.CallReceiver.putSelector(CallReceiver.java:151)
	at org.jetbrains.kotlin.codegen.StackValue.put(StackValue.java:105)
	at org.jetbrains.kotlin.codegen.StackValue.put(StackValue.java:98)
	at org.jetbrains.kotlin.codegen.ExpressionCodegen.putReceiverAndInlineMarkerIfNeeded(ExpressionCodegen.java:2300)
	at org.jetbrains.kotlin.codegen.ExpressionCodegen.invokeMethodWithArguments(ExpressionCodegen.java:2234)
	at org.jetbrains.kotlin.codegen.ExpressionCodegen.invokeMethodWithArguments(ExpressionCodegen.java:2221)
	at org.jetbrains.kotlin.codegen.Callable$invokeMethodWithArguments$1.invoke(Callable.kt:44)
	at org.jetbrains.kotlin.codegen.Callable$invokeMethodWithArguments$1.invoke(Callable.kt:23)
	at org.jetbrains.kotlin.codegen.OperationStackValue.putSelector(StackValue.kt:75)
	at org.jetbrains.kotlin.codegen.StackValue.put(StackValue.java:105)
	at org.jetbrains.kotlin.codegen.StackValue.put(StackValue.java:98)
	at org.jetbrains.kotlin.codegen.ExpressionCodegen.putStackValue(ExpressionCodegen.java:348)
	at org.jetbrains.kotlin.codegen.ExpressionCodegen.gen(ExpressionCodegen.java:333)
	at org.jetbrains.kotlin.codegen.ExpressionCodegen.returnExpression(ExpressionCodegen.java:1582)
	at org.jetbrains.kotlin.codegen.FunctionGenerationStrategy$FunctionDefault.doGenerateBody(FunctionGenerationStrategy.java:56)
	at org.jetbrains.kotlin.codegen.FunctionGenerationStrategy$CodegenBased.generateBody(FunctionGenerationStrategy.java:76)
	at org.jetbrains.kotlin.codegen.FunctionCodegen.generateMethodBody(FunctionCodegen.java:570)
	at org.jetbrains.kotlin.codegen.FunctionCodegen.generateMethodBody(FunctionCodegen.java:333)
	at org.jetbrains.kotlin.codegen.FunctionCodegen.generateMethod(FunctionCodegen.java:299)
	at org.jetbrains.kotlin.codegen.FunctionCodegen.generateMethod(FunctionCodegen.java:177)
	at org.jetbrains.kotlin.codegen.FunctionCodegen.gen(FunctionCodegen.java:148)
	at org.jetbrains.kotlin.codegen.MemberCodegen.genSimpleMember(MemberCodegen.java:210)
	at org.jetbrains.kotlin.codegen.PackagePartCodegen.generateBody(PackagePartCodegen.java:95)
	at org.jetbrains.kotlin.codegen.MemberCodegen.generate(MemberCodegen.java:142)
	at org.jetbrains.kotlin.codegen.PackageCodegenImpl.generateFile(PackageCodegenImpl.java:127)
	at org.jetbrains.kotlin.codegen.PackageCodegenImpl.generate(PackageCodegenImpl.java:66)
	at org.jetbrains.kotlin.codegen.KotlinCodegenFacade.generatePackage(KotlinCodegenFacade.java:100)
	at org.jetbrains.kotlin.codegen.KotlinCodegenFacade.doGenerateFiles(KotlinCodegenFacade.java:78)
	at org.jetbrains.kotlin.codegen.KotlinCodegenFacade.compileCorrectFiles(KotlinCodegenFacade.java:45)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.generate(KotlinToJVMBytecodeCompiler.kt:450)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules(KotlinToJVMBytecodeCompiler.kt:152)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:158)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:61)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.java:107)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.java:51)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:92)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl$compile$$inlined$ifAlive$lambda$1.invoke(CompileServiceImpl.kt:380)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl$compile$$inlined$ifAlive$lambda$1.invoke(CompileServiceImpl.kt:96)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl$doCompile$$inlined$ifAlive$lambda$2.invoke(CompileServiceImpl.kt:892)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl$doCompile$$inlined$ifAlive$lambda$2.invoke(CompileServiceImpl.kt:96)
	at org.jetbrains.kotlin.daemon.common.DummyProfiler.withMeasure(PerfUtils.kt:137)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl.checkedCompile(CompileServiceImpl.kt:919)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl.doCompile(CompileServiceImpl.kt:891)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl.compile(CompileServiceImpl.kt:378)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:346)
	at sun.rmi.transport.Transport$1.run(Transport.java:200)
	at sun.rmi.transport.Transport$1.run(Transport.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.rmi.transport.Transport.serviceCall(Transport.java:196)
	at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:568)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:826)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:683)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:682)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalStateException: Cannot serialize error type: [ERROR : Unknown type parameter 2]
	at org.jetbrains.kotlin.serialization.SerializerExtension.serializeErrorType(SerializerExtension.kt:62)
	at org.jetbrains.kotlin.codegen.serialization.JvmSerializerExtension.serializeErrorType(JvmSerializerExtension.java:210)
	at org.jetbrains.kotlin.serialization.DescriptorSerializer.type$serialization(DescriptorSerializer.kt:464)
	at org.jetbrains.kotlin.serialization.DescriptorSerializer.typeArgument(DescriptorSerializer.kt:567)
	at org.jetbrains.kotlin.serialization.DescriptorSerializer.fillFromPossiblyInnerType(DescriptorSerializer.kt:535)
	at org.jetbrains.kotlin.serialization.DescriptorSerializer.type$serialization(DescriptorSerializer.kt:493)
	at org.jetbrains.kotlin.serialization.DescriptorSerializer.type$serialization(DescriptorSerializer.kt:517)
	at org.jetbrains.kotlin.serialization.DescriptorSerializer.typeArgument(DescriptorSerializer.kt:567)
	at org.jetbrains.kotlin.serialization.DescriptorSerializer.fillFromPossiblyInnerType(DescriptorSerializer.kt:535)
	at org.jetbrains.kotlin.serialization.DescriptorSerializer.type$serialization(DescriptorSerializer.kt:493)
	at org.jetbrains.kotlin.serialization.DescriptorSerializer.typeArgument(DescriptorSerializer.kt:567)
	at org.jetbrains.kotlin.serialization.DescriptorSerializer.fillFromPossiblyInnerType(DescriptorSerializer.kt:535)
	at org.jetbrains.kotlin.serialization.DescriptorSerializer.type$serialization(DescriptorSerializer.kt:493)
	at org.jetbrains.kotlin.serialization.DescriptorSerializer.functionProto(DescriptorSerializer.kt:263)
	at org.jetbrains.kotlin.codegen.ClosureCodegen.generateKotlinMetadataAnnotation(ClosureCodegen.java:243)
	at org.jetbrains.kotlin.codegen.MemberCodegen.generate(MemberCodegen.java:149)
	at org.jetbrains.kotlin.codegen.ExpressionCodegen.genClosure(ExpressionCodegen.java:980)
	at org.jetbrains.kotlin.codegen.ExpressionCodegen.genClosure(ExpressionCodegen.java:954)
	at org.jetbrains.kotlin.codegen.ExpressionCodegen.visitLambdaExpression(ExpressionCodegen.java:945)
	at org.jetbrains.kotlin.codegen.ExpressionCodegen.visitLambdaExpression(ExpressionCodegen.java:119)
	at org.jetbrains.kotlin.psi.KtLambdaExpression.accept(KtLambdaExpression.java:37)
	at org.jetbrains.kotlin.codegen.ExpressionCodegen.genQualified(ExpressionCodegen.java:306)
	... 74 more
```

### CODE REVIEW

**Comment by raulraja** [comment]
@nomisRev that is definitely a Kotlin compiler bug and should probably be reported.

**Comment by raulraja** [comment]
Regarding the function to emulate the `invoke` I think it's a valid solution and this encoding is better than what we have.

**Comment by nomisRev** [comment]
@raulraja I think I somewhat managed to get a cleaner API and implementation of `IndexedStateT` but I bumped into something weird. Given following type and state definitions

```kotlin
sealed class DoorState
object Open : DoorState()
object Closed : DoorState()

fun open(): IndexedState<Closed, Open, Unit> = IndexedState.set(Open)
fun close(): IndexedState<Open, Closed, Unit> = IndexedState.set(Closed)
```

I was hoping to get the same behavior as [Cats IndexedStateT for](https://typelevel.org/cats/datatypes/state#changing-states).
```kotlin
fun invalidDoorOperations() = IndexedState().monad<DoorState>().binding<IndexedStateKindPartial<DoorState, DoorState>, Unit> {
    val a = open().bind()
    val b = close().bind()
    val c = close().bind()
    yields(Unit)
}.ev()

invalidDoorOperations().runM(Closed).value().a.let(::println) //kategory.Closed@6f539caf
```

while flatMapping fails at compile time although it is with a very vague compile error...

```kotlin
open().flatMap {
        close().flatMap {
            close()
        }
    }.ev().runM(Closed).value().a.let(::println)
```

I am not sure if this can be fixed as `for` in Scala is syntactic sugar and is translated to `flatMap` and thus works the same as above `flatMap` code. But with our version of monadic binding I am forced to fix the type params for the binding block with `DoorState`. Am I missing something? Or any ideas how we could solves this?

**Comment by nomisRev** [comment]
This should be about it. If you take a look at docs the API did not break, beside the convenience methods to retrieve instances for State. And above mentioned type bug with binding.

Also I am not sure how I can fix above mentioned behavior or if it is even possible.

Beside that only docs for `IndexedState` and `IndexedStateT` must be written. Shall I include that in this PR?

**Comment by raulraja** [comment]
It'd be great to have docs in this PR but it's not critical if you need this to continue some of the other work.
As for the binding issue, do you also get it when using `IndexStateT` over `Id` or `Eval` instead of the already applied version?

**Comment by nomisRev** [comment]
Yes same behavior when using `IndexStateT<IdHK, _, _ , _>` or `IndexStateT<EvalHK, _, _ , _>`. We "bind" the value from `flatMap` in the coroutine so we lose the type we have to return, right?

Shouldn't be a problem to whip up some docs 👍

**Comment by raulraja** [comment]
@nomisRev if the monad instance is properly parametric the returning result type should be that of the kind representation that should be compatible with state changes as in the example. I'd have to take a closer look but swamped with work this week. It'd help if we can do a team viewer session or something where we can discuss it live over hangouts. Let's catch up one of these evenings this week and we can give it a shot together if you are up for that.

**Comment by nomisRev** [comment]
@raulraja sounds good! Hit me up on slack if you have some time.

**Comment by nomisRev** [comment]
I am going to close this PR for now since there are some issues that hinder completion. I am going to leave the branch alive for now.

**Pull request closed without merging**
