### PR TITLE
fix maven url for documentation

### PR DESCRIPTION
**Pull request by dgoetsch**
I haven't used kategory.  I read about it on a blog post, and thought I'd try it out.

I noticed this small documentation discrepancy when trying to set up the project locally.

### CODE REVIEW

**Comment by pakoito** [comment]
@dgoetsch Thank you for your contribution. Do you mind if I ask you which blog post? Was it Jorge's?

**Comment by dgoetsch** [comment]
Yes, it was this one: https://medium.com/@JorgeCastilloPr/kotlin-functional-programming-does-it-make-sense-36ad07e6bacf

I've been using funktionale for several months, but have been somewhat dissatisfied, kategory seems interesting.

**Comment by pakoito** [comment]
@dgoetsch Come to gitter and we can chat about what did you expect from funktionale https://gitter.im/kategory/Lobby

**Comment by dgoetsch** [comment]
I'm not sure why the build failed.  It seemed vague.. "No outputs for 10 minutes".

```
...
warning: library has Kotlin runtime bundled into it
WARN: [kts] kotlin.script.experimental.dependencies.DependenciesResolver.NoDependencies must have a constructor without required parameters
:runAnk -> Compiling: /home/travis/build/kategory/kategory/kategory-docs/build/site/docs/datatypes/setkw/README.md
:runAnk -> Compiling: /home/travis/build/kategory/kategory/kategory-docs/build/site/docs/datatypes/coyoneda/README.md
:runAnk -> Compiling: /home/travis/build/kategory/kategory/kategory-docs/build/site/docs/datatypes/try/README.md
:runAnk -> Compiling: /home/travis/build/kategory/kategory/kategory-docs/build/site/docs/datatypes/freeapplicative/README.md
:runAnk -> Compiling: /home/travis/build/kategory/kategory/kategory-docs/build/site/docs/datatypes/cofree/README.md
:runAnk -> Compiling: /home/travis/build/kategory/kategory/kategory-docs/build/site/docs/datatypes/reader/README.md
:runAnk -> Compiling: /home/travis/build/kategory/kategory/kategory-docs/build/site/docs/datatypes/yoneda/README.md
:runAnk -> Compiling: /home/travis/build/kategory/kategory/kategory-docs/build/site/docs/datatypes/ior/README.md
warning: some JAR files in the classpath have the Kotlin Runtime library bundled into them. This may cause difficult to debug problems if there's a different version of the Kotlin Runtime library in the classpath. Consider removing these libraries from the classpath or use '-Xskip-runtime-version-check' to suppress this warning
warning: library has Kotlin runtime bundled into it
WARN: [kts] kotlin.script.experimental.dependencies.DependenciesResolver.NoDependencies must have a constructor without required parameters
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received
The build has been terminated```

The build completed on my machine in 13 minutes 24 seconds (i7, 16gb RAM,Linux, Gradle 4.2.1)

I'm not sure why the change I made would cause a build to fail.. anybody have ideas?

**Comment by pakoito** [comment]
@dgoetsch Ank, our snippet compiler, sometimes takes longer than what Travis allows. We're trying to figure out why.

**Comment by raulraja** [comment]
It's not ANK, it's the Kotlin Script Engine that trips on coroutines and other stuff on an endless loop. We need to find a replacement for that.

**Comment by pakoito** [comment]
Apologies for the delay. I've been doing the merge, wait for CI, forget about it like 10 times. I'll push without CI now.

**Pull request merged**
