### PR TITLE
#213: Dedupe law tests

### PR DESCRIPTION
**Pull request by groodt**
Addresses issue #213 

I've only modified kategory-core. If the approach I've taken is desired, then I'll continue to apply to the other modules.

### CODE REVIEW

**Comment by raulraja** [comment]
👏 👏 👏 👏

**Comment by groodt** [comment]
Ok, the changes are in. Tests are all passing. Awesome! 👍

**Comment by pakoito** [comment]
@groodt One last change: FlowableKW has multiple tests for different permutations of backpressure strategy & flat/concat/switch. These tests are not duplicates but are filtered out. Could you please move every permutation into one different call to testLaws()

**Comment by groodt** [comment]
@pakoito Good spot! I think I've split them out now. Please take a look.

**Comment by pakoito** [comment]
@groodt Sadly I don't believe we can dedupe any of the permutations. Could you please revert it to what it was before this PR, where every permutation is its own testLaws()?

**Comment by groodt** [comment]
@pakoito Ok, I've reverted the changes to ```FlowableKWTests```

**Comment by raulraja** [comment]
@groodt thanks for your contribution, this is awesome!

**Pull request merged**
